param(
    [Parameter(Mandatory=$true)]
    [string]$InputBin,

    [Parameter(Mandatory=$true)]
    [string]$OutputHex,

    [Parameter(Mandatory=$true)]
    [string]$ProgramInfo
)

$inputPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($InputBin)
$outputPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($OutputHex)
$infoPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($ProgramInfo)

[byte[]]$bytes = [System.IO.File]::ReadAllBytes($inputPath)
$words = New-Object System.Collections.Generic.List[string]

for ($i = 0; $i -lt $bytes.Length; $i += 4) {
    $b0 = [uint32]0
    $b1 = [uint32]0
    $b2 = [uint32]0
    $b3 = [uint32]0

    if ($i -lt $bytes.Length) {
        $b0 = [uint32]$bytes[$i]
    }
    if (($i + 1) -lt $bytes.Length) {
        $b1 = [uint32]$bytes[$i + 1]
    }
    if (($i + 2) -lt $bytes.Length) {
        $b2 = [uint32]$bytes[$i + 2]
    }
    if (($i + 3) -lt $bytes.Length) {
        $b3 = [uint32]$bytes[$i + 3]
    }

    $word = $b0 -bor ($b1 -shl 8) -bor ($b2 -shl 16) -bor ($b3 -shl 24)
    $words.Add(("{0:x8}" -f $word))
}

[System.IO.File]::WriteAllLines($outputPath, $words)

$instructionCount = $words.Count
$tick = [char]96
$info = @(
    "// Auto-generated by tools/bin_to_word_hex.ps1"
    ("{0}define PROGRAM_INSTRS {1}" -f $tick, $instructionCount)
)
[System.IO.File]::WriteAllLines($infoPath, $info)
