param(
    [Parameter(Mandatory=$true)]
    [string]$InputHex,

    [Parameter(Mandatory=$true)]
    [string]$ProgramInfo
)

$inputPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($InputHex)
$infoPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($ProgramInfo)

$instructionCount = 0
foreach ($line in [System.IO.File]::ReadLines($inputPath)) {
    $clean = $line.Split('/')[0].Trim()
    if ($clean -match '^[0-9a-fA-F]{1,8}$') {
        $instructionCount = $instructionCount + 1
    }
}

if ($instructionCount -lt 1) {
    $instructionCount = 1
}

$tick = [char]96
$info = @(
    "// Auto-generated by tools/update_program_info_from_hex.ps1"
    ("{0}define PROGRAM_INSTRS {1}" -f $tick, $instructionCount)
)
[System.IO.File]::WriteAllLines($infoPath, $info)
